### ISSUE TITLE
Async support?

### ISSUE THREAD

**Issue by robertgonzales** [socketsupply/union-app-studio#23]
First, just want to say how much I love this tool! It's already been super useful for mentoring and demonstrations.

I noticed that any logs called asynchronously fail to display in the preview. Are there plans to support this?
```
setTimeout(() => console.log("delay"), 100)
fetch(someApi).then(result => console.log(result))
```

**Comment by heapwolf** [comment]
@robertgonzales thank you!! and thanks for pointing out the issue! I didn't notice this at first because the fetch requests i was doing worked, but i wasn't logging the data to the output panel. This should be working now in the `0.0.6` release, but feel free to reopen if anything doesn't look right.
