### ISSUE TITLE
context

### ISSUE THREAD

**Issue by juliangruber** [socketsupply/union-app-studio#3]
It would be great to keep context between code blocks, so something like this is possible:

```js
const concat = (a, b) => a + b



concat('hello', 'world')
```

**Comment by heapwolf** [comment]
In release 0.0.2 I made it so that the entire source text is evaluated and the result output panel is just what is logged by `console.log`. Having each block evaluate as an expression and print to the output window might lead to some unexpected values. Maybe it can be done without being confusing, maybe as a mode?

**Comment by heapwolf** [comment]
This is fixed now.
